name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check for errors related with PHP Community Standards
        run: bash ${GITHUB_WORKSPACE}/run-tests.sh
