name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - shell: bash
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Check for errors related with PHP Community Standards
        run: cd ../../ && sh run-test.sh
