# Source: https://github.com/WordPress/WordPress-Coding-Standards/wiki/Running-in-GitHub-Actions
name: phpcs

on:
  push:
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancel all previous workflow runs for the same branch that have not yet completed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  phpcs:
    runs-on: ubuntu-latest
    name: PHPCS
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "latest"
          ini-values: "memory_limit=1G"
          coverage: none
          tools: cs2pr, phpcs, php-cs-fixer, phpunit

      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v3"
        with:
          # Bust the cache at least once a month - output format: YYYY-MM.
          custom-cache-suffix: $(date -u "+%Y-%m")

      - name: Add WordPress Coding Standards sniffs
        run: |
          phpcs --config-set installed_paths ../../wp-coding-standards/wpcs/WordPress
          phpcs --config-set installed_paths ../../wp-coding-standards/wpcs/WordPress-Core
          phpcs --config-set installed_paths ../../wp-coding-standards/wpcs/WordPress-Docs
          phpcs --config-set installed_paths ../../wp-coding-standards/wpcs/WordPress-Extra
          phpcs -i

      - name: Run PHPCS checks
        id: phpcs
        run: phpcs --report-full --report-checkstyle=./phpcs.xml

      - name: Show PHPCS results in PR
        if: ${{ always() && steps.phpcs.outcome == 'failure' }}
        run: cs2pr ./phpcs.xml
